title: Stack Problems
description: 朝花夕拾
author: April01xxx
github: https://github.com/April01xxx
about: 你瞧这些白云聚了又散，散了又聚，人生离合，亦复如斯。 --金庸 <<神雕侠侣>>
disqus_shortname: stackproblems
google_analytics: UA-XXXXXXXX-Y
avatar_url: /static/img/avatar.jpg

enableTags: true
tagarray: []

social:
    - icon: fa-facebook
      link: "#"
    - icon: fa-twitter
      link: "#"
    - icon: fa-linkedin
      link: "#"
    - icon: fa-stack-exchange
      link: "#"
    - icon: fa-github
      link: "https://github.com/April01xxx"

urls:
    - text: About Me
      url: /about/

url: "https://April01xxx.github.io"
baseurl: ""
paginate: 20
per_page: 20
paginate_path: "/page/:num/"
markdown: kramdown
gems:
  - jekyll-paginate
  - jekyll-gist

compress_html:
  clippings: all
  comments: ["<!-- ", " -->"]
  endings: all
  ignore:
    envs: ['development']
